source 'https://cdn.cocoapods.org/'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WMZTagsDemo' do
  inhibit_all_warnings!
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for WMZTagsDemo
  pod 'TTGTagCollectionView'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
          end
      end
  end

end
